config_setting(
    name = "with_openssl",
    define_values = {
        "with_openssl": "false",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "with_sys_zlib",
    define_values = {
        "with_sys_zlib": "false",
    },
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "compiler",
    srcs = [
        "compiler/cpp/thriftl.cc",
        "compiler/cpp/thrifty.cc",
        "compiler/cpp/thrifty.h",
        "compiler/cpp/version.h",
    ] + glob([
        "compiler/cpp/src/**/*.c",
        "compiler/cpp/src/**/*.cc",
        "compiler/cpp/src/**/*.h",
    ]),
    copts = [
        "-Wall",
        "-Wno-sign-compare",
        "-Wno-unused",
        "-Wno-literal-suffix",
    ],
    includes = [
        "compiler/cpp",
        "compiler/cpp/src",
    ],
    linkopts = ["-lfl"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "thrift",
    srcs = [
        "lib/cpp/src/thrift/TOutput.cpp",
        "lib/cpp/src/thrift/TApplicationException.cpp",
        "lib/cpp/src/thrift/VirtualProfiling.cpp",
        "lib/cpp/src/thrift/async/TAsyncChannel.cpp",
        "lib/cpp/src/thrift/async/TConcurrentClientSyncInfo.cpp",
        "lib/cpp/src/thrift/concurrency/Monitor.cpp",
        "lib/cpp/src/thrift/concurrency/Mutex.cpp",
        "lib/cpp/src/thrift/concurrency/PosixThreadFactory.cpp",
        "lib/cpp/src/thrift/concurrency/ThreadManager.cpp",
        "lib/cpp/src/thrift/concurrency/TimerManager.cpp",
        "lib/cpp/src/thrift/concurrency/Util.cpp",
        "lib/cpp/src/thrift/processor/PeekProcessor.cpp",
        "lib/cpp/src/thrift/protocol/TBase64Utils.cpp",
        "lib/cpp/src/thrift/protocol/TDebugProtocol.cpp",
        "lib/cpp/src/thrift/protocol/TJSONProtocol.cpp",
        "lib/cpp/src/thrift/protocol/TMultiplexedProtocol.cpp",
        "lib/cpp/src/thrift/protocol/TProtocol.cpp",
        "lib/cpp/src/thrift/server/TServer.cpp",
        "lib/cpp/src/thrift/server/TSimpleServer.cpp",
        "lib/cpp/src/thrift/server/TServerFramework.cpp",
        "lib/cpp/src/thrift/server/TThreadPoolServer.cpp",
        "lib/cpp/src/thrift/server/TThreadedServer.cpp",
        "lib/cpp/src/thrift/server/TConnectedClient.cpp",
        "lib/cpp/src/thrift/transport/TBufferTransports.cpp",
        "lib/cpp/src/thrift/transport/TFDTransport.cpp",
        "lib/cpp/src/thrift/transport/TFileTransport.cpp",
        "lib/cpp/src/thrift/transport/THttpClient.cpp",
        "lib/cpp/src/thrift/transport/THttpServer.cpp",
        "lib/cpp/src/thrift/transport/THttpTransport.cpp",
        "lib/cpp/src/thrift/transport/TPipe.cpp",
        "lib/cpp/src/thrift/transport/TPipeServer.cpp",
        "lib/cpp/src/thrift/transport/TSSLServerSocket.cpp",
        "lib/cpp/src/thrift/transport/TSSLSocket.cpp",
        "lib/cpp/src/thrift/transport/TServerSocket.cpp",
        "lib/cpp/src/thrift/transport/TSimpleFileTransport.cpp",
        "lib/cpp/src/thrift/transport/TSocket.cpp",
        "lib/cpp/src/thrift/transport/TSocketPool.cpp",
        "lib/cpp/src/thrift/transport/TTransportException.cpp",
        "lib/cpp/src/thrift/transport/TTransportUtils.cpp",
    ],
    hdrs = [
        "lib/cpp/src/thrift/TApplicationException.h",
        "lib/cpp/src/thrift/TDispatchProcessor.h",
        "lib/cpp/src/thrift/TLogging.h",
        "lib/cpp/src/thrift/TProcessor.h",
        "lib/cpp/src/thrift/Thrift.h",
        "lib/cpp/src/thrift/TToString.h",
        "lib/cpp/src/thrift/async/TAsyncChannel.h",
        "lib/cpp/src/thrift/async/TConcurrentClientSyncInfo.h",
        "lib/cpp/src/thrift/concurrency/Exception.h",
        "lib/cpp/src/thrift/concurrency/FunctionRunner.h",
        "lib/cpp/src/thrift/concurrency/Monitor.h",
        "lib/cpp/src/thrift/concurrency/Mutex.h",
        "lib/cpp/src/thrift/concurrency/PlatformThreadFactory.h",
        "lib/cpp/src/thrift/concurrency/PosixThreadFactory.h",
        "lib/cpp/src/thrift/concurrency/Thread.h",
        "lib/cpp/src/thrift/concurrency/ThreadManager.h",
        "lib/cpp/src/thrift/concurrency/TimerManager.h",
        "lib/cpp/src/thrift/concurrency/Util.h",
        "lib/cpp/src/thrift/cxxfunctional.h",
        "lib/cpp/src/thrift/processor/PeekProcessor.h",
        "lib/cpp/src/thrift/processor/StatsProcessor.h",
        "lib/cpp/src/thrift/processor/TMultiplexedProcessor.h",
        "lib/cpp/src/thrift/protocol/TBase64Utils.h",
        "lib/cpp/src/thrift/protocol/TBinaryProtocol.h",
        "lib/cpp/src/thrift/protocol/TBinaryProtocol.tcc",
        "lib/cpp/src/thrift/protocol/TCompactProtocol.h",
        "lib/cpp/src/thrift/protocol/TCompactProtocol.tcc",
        "lib/cpp/src/thrift/protocol/TDebugProtocol.h",
        "lib/cpp/src/thrift/protocol/TJSONProtocol.h",
        "lib/cpp/src/thrift/protocol/TMultiplexedProtocol.h",
        "lib/cpp/src/thrift/protocol/TProtocol.h",
        "lib/cpp/src/thrift/protocol/TProtocolDecorator.h",
        "lib/cpp/src/thrift/protocol/TProtocolException.h",
        "lib/cpp/src/thrift/protocol/TProtocolTap.h",
        "lib/cpp/src/thrift/protocol/TVirtualProtocol.h",
        "lib/cpp/src/thrift/server/TServer.h",
        "lib/cpp/src/thrift/server/TSimpleServer.h",
        "lib/cpp/src/thrift/server/TServerFramework.h",
        "lib/cpp/src/thrift/server/TThreadPoolServer.h",
        "lib/cpp/src/thrift/server/TThreadedServer.h",
        "lib/cpp/src/thrift/server/TConnectedClient.h",
        "lib/cpp/src/thrift/config.h",
        "lib/cpp/src/thrift/TOutput.h",
        "lib/cpp/src/thrift/thrift-config.h",
        "lib/cpp/src/thrift/transport/PlatformSocket.h",
        "lib/cpp/src/thrift/transport/TBufferTransports.h",
        "lib/cpp/src/thrift/transport/TFDTransport.h",
        "lib/cpp/src/thrift/transport/TFileTransport.h",
        "lib/cpp/src/thrift/transport/THttpClient.h",
        "lib/cpp/src/thrift/transport/THttpServer.h",
        "lib/cpp/src/thrift/transport/THttpTransport.h",
        "lib/cpp/src/thrift/transport/TPipe.h",
        "lib/cpp/src/thrift/transport/TPipeServer.h",
        "lib/cpp/src/thrift/transport/TSSLServerSocket.h",
        "lib/cpp/src/thrift/transport/TSSLSocket.h",
        "lib/cpp/src/thrift/transport/TServerSocket.h",
        "lib/cpp/src/thrift/transport/TServerTransport.h",
        "lib/cpp/src/thrift/transport/TShortReadTransport.h",
        "lib/cpp/src/thrift/transport/TSimpleFileTransport.h",
        "lib/cpp/src/thrift/transport/TSocket.h",
        "lib/cpp/src/thrift/transport/TSocketPool.h",
        "lib/cpp/src/thrift/transport/TTransport.h",
        "lib/cpp/src/thrift/transport/TTransportException.h",
        "lib/cpp/src/thrift/transport/TTransportUtils.h",
        "lib/cpp/src/thrift/transport/TVirtualTransport.h",
    ],
    copts = ["-Wall"],
    defines = ["HAVE_CONFIG_H"],
    includes = [
        "lib/cpp",
        "lib/cpp/src",
        "lib/cpp/src/thrift",
    ],
    linkopts = select({
        ":with_openssl": [
            "-lssl",
            "-lcrypto",
        ],
        "//conditions:default": [],
    }) + [
        "-lrt",
        "-lpthread",
    ],
    visibility = ["//visibility:public"],
    deps = select({
        ":with_openssl": [],
        "//conditions:default": ["//external:ssl"],
    }) + [
        "@boost//:algorithm",
        "@boost//:lexical_cast",
        "@boost//:smart_ptr",
        "@boost//:tokenizer",
    ],
)

cc_library(
    name = "thriftz",
    srcs = ["lib/cpp/src/thrift/transport/TZlibTransport.cpp"],
    hdrs = ["lib/cpp/src/thrift/transport/TZlibTransport.h"],
    copts = ["-Wall"],
    includes = [
        "lib/cpp/src",
        "lib/cpp/src/thrift",
    ],
    linkopts = select({
        "with_sys_zlib": ["-lz"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":thrift",
    ] + select({
        "with_sys_zlib": [],
        "//conditions:default": ["//external:zlib"],
    }),
)

cc_library(
    name = "thriftnb",
    srcs = [
        "lib/cpp/src/thrift/async/TAsyncProtocolProcessor.cpp",
        "lib/cpp/src/thrift/async/TEvhttpClientChannel.cpp",
        "lib/cpp/src/thrift/async/TEvhttpServer.cpp",
        "lib/cpp/src/thrift/server/TNonblockingServer.cpp",
    ],
    hdrs = [
        "lib/cpp/src/thrift/async/TAsyncBufferProcessor.h",
        "lib/cpp/src/thrift/async/TAsyncDispatchProcessor.h",
        "lib/cpp/src/thrift/async/TAsyncProcessor.h",
        "lib/cpp/src/thrift/async/TAsyncProtocolProcessor.h",
        "lib/cpp/src/thrift/async/TEvhttpClientChannel.h",
        "lib/cpp/src/thrift/async/TEvhttpServer.h",
        "lib/cpp/src/thrift/server/TNonblockingServer.h",
    ],
    copts = ["-Wall"],
    includes = [
        "lib/cpp/src",
        "lib/cpp/src/thrift",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":thrift",
        "@libevent",
    ],
)
